"use client"
import { Download, TrendingDown, TrendingUp } from "lucide-react"
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts"
import { FinancePageShell, StatCard } from "@/components/finance-page-shell"
const monthly=[{m:"Mar",v:42},{m:"Apr",v:58},{m:"May",v:51},{m:"Jun",v:76},{m:"Jul",v:69},{m:"Aug",v:88}]
const categories=[{n:"Operations",v:38,c:"#86efac"},{n:"Technology",v:26,c:"#63b3ed"},{n:"Logistics",v:21,c:"#f6ad55"},{n:"Facilities",v:15,c:"#555"}]
const vendors=[{n:"Nile Energy",v:72},{n:"Africa Logistics",v:58},{n:"Kampala Office",v:47},{n:"Eastline Tech",v:35},{n:"Crestwood",v:24}]
export default function Analytics(){return <FinancePageShell title="Analytics" description="Understand spend, cash flow, and payment performance." action={<button className="flex h-11 items-center gap-2 rounded-xl border border-[#292929] px-4 text-xs text-[#aaa]"><Download className="h-4 w-4"/>Export report</button>}>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total spend" value="$364,820" detail="+12.4% vs last period"/><StatCard label="Average invoice" value="$1,471" detail="Across 248 invoices"/><StatCard label="Average payment time" value="18.4 days" detail="2.1 days faster" color="text-[#86efac]"/><StatCard label="Overdue rate" value="7.6%" detail="Down from 9.2%" color="text-amber-300"/></div>
 <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-6"><div className="flex justify-between"><div><h2 className="font-medium">Spend over time</h2><p className="mt-1 text-xs text-[#666]">Approved invoice value, USD thousands</p></div><span className="flex h-fit items-center gap-1 rounded-full bg-[#86efac]/10 px-2 py-1 text-[10px] text-[#86efac]"><TrendingUp className="h-3 w-3"/>12.4%</span></div><div className="mt-6 h-72"><ResponsiveContainer><AreaChart data={monthly}><defs><linearGradient id="a" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#86efac" stopOpacity=".3"/><stop offset="1" stopColor="#86efac" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#1c1c1c"/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fill:'#555',fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#555',fontSize:11}}/><Tooltip contentStyle={{background:'#151515',border:'1px solid #292929',borderRadius:10}}/><Area dataKey="v" stroke="#86efac" fill="url(#a)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></div>
 <div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-6"><h2 className="font-medium">Spend by category</h2><p className="mt-1 text-xs text-[#666]">Current period allocation</p><div className="h-52"><ResponsiveContainer><PieChart><Pie data={categories} dataKey="v" innerRadius={58} outerRadius={80} paddingAngle={3}>{categories.map(x=><Cell key={x.n} fill={x.c}/>)}</Pie></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3">{categories.map(x=><div key={x.n} className="flex items-center gap-2 text-xs text-[#777]"><i className="h-2 w-2 rounded-full" style={{background:x.c}}/><span>{x.n}</span><b className="ml-auto text-[#bbb]">{x.v}%</b></div>)}</div></div></div>
 <div className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-6"><h2 className="font-medium">Top vendors by spend</h2><div className="mt-5 h-60"><ResponsiveContainer><BarChart data={vendors} layout="vertical"><XAxis type="number" hide/><YAxis dataKey="n" type="category" axisLine={false} tickLine={false} tick={{fill:'#777',fontSize:11}} width={110}/><Bar dataKey="v" fill="#86efac" radius={[0,5,5,0]} barSize={15}/></BarChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-6"><h2 className="font-medium">Payment health</h2><div className="mt-6 space-y-5">{[["Paid on time","82%","bg-[#86efac]"],["Paid late","11%","bg-amber-300"],["Currently overdue","7%","bg-red-300"]].map(x=><div key={x[0]}><div className="mb-2 flex justify-between text-xs"><span className="text-[#777]">{x[0]}</span><span>{x[1]}</span></div><div className="h-2 rounded-full bg-[#222]"><div className={`h-full rounded-full ${x[2]}`} style={{width:x[1]}}/></div></div>)}</div><div className="mt-7 flex items-center gap-3 rounded-xl bg-[#121212] p-4"><TrendingDown className="h-5 w-5 text-[#86efac]"/><p className="text-xs leading-5 text-[#888]">Late payments decreased by <b className="text-white">3.2%</b> compared with last month.</p></div></div></div>
 </FinancePageShell>}
