"use client"
import { useState } from "react"
import { CheckCircle2, Clock3, Mail, MessageSquare, Send } from "lucide-react"
import { FinancePageShell, StatCard } from "@/components/finance-page-shell"
const drafts=[{to:"Nile Energy Systems",subject:"Payment overdue — NES/4491/26",body:"Hi Sarah, this is a friendly reminder that invoice NES/4491/26 for $23,170.00 was due four days ago. Could you please confirm the payment status?",tag:"Overdue"},{to:"Gulu Trade Partners",subject:"Missing tax information",body:"Hello, while processing invoice GTP-10094, we noticed the tax identification number was missing. Please share an updated copy when convenient.",tag:"Missing data"},{to:"Eastline Technologies",subject:"Invoice ET-88420 received",body:"Thanks for sending your invoice. Our finance team is reviewing the document and will confirm once it has been approved.",tag:"Acknowledgement"}]
export default function FollowUps(){const [sent,setSent]=useState<string[]>([]);return <FinancePageShell title="Follow-ups" description="AI-drafted vendor messages, ready for your approval.">
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Ready to send" value="4" detail="AI drafted" color="text-[#86efac]"/><StatCard label="Scheduled" value="8" detail="Next 7 days"/><StatCard label="Sent this month" value="37" detail="71% opened"/><StatCard label="Replies received" value="19" detail="51% response rate"/></div>
 <div className="grid gap-5 lg:grid-cols-[1.5fr_.75fr]"><div className="space-y-3">{drafts.map(d=><div key={d.subject} className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#86efac]/10 text-[#86efac]"><Mail className="h-4 w-4"/></span><div><div className="flex items-center gap-2"><p className="text-sm font-medium">{d.to}</p><span className="rounded-full bg-[#1d1d1d] px-2 py-1 text-[9px] text-[#777]">{d.tag}</span></div><p className="mt-1 text-xs text-[#777]">{d.subject}</p></div></div>{sent.includes(d.subject)?<span className="flex items-center gap-2 text-xs text-[#86efac]"><CheckCircle2 className="h-4 w-4"/>Sent</span>:<div className="flex gap-2"><button className="rounded-lg border border-[#292929] px-3 py-2 text-[10px] text-[#777]">Edit</button><button onClick={()=>setSent([...sent,d.subject])} className="flex items-center gap-2 rounded-lg bg-[#86efac] px-3 py-2 text-[10px] font-semibold text-black"><Send className="h-3 w-3"/>Send now</button></div>}</div><p className="mt-4 rounded-xl bg-[#121212] p-4 text-xs leading-6 text-[#999]">{d.body}</p></div>)}</div>
 <div className="space-y-5"><div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-5"><h2 className="text-sm font-medium">Automation rules</h2><div className="mt-4 space-y-3">{[["Overdue reminder","3 days after due"],["Second reminder","7 days after due"],["Receipt confirmation","On every upload"]].map(x=><div key={x[0]} className="flex items-center gap-3 rounded-xl bg-[#121212] p-3"><span className="h-2 w-2 rounded-full bg-[#86efac]"/><div><p className="text-xs text-[#ccc]">{x[0]}</p><p className="mt-1 text-[10px] text-[#666]">{x[1]}</p></div></div>)}</div><button className="mt-4 w-full rounded-xl border border-[#292929] py-2.5 text-xs text-[#888]">Manage automations</button></div><div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-5"><h2 className="text-sm font-medium">Channels</h2><div className="mt-4 flex gap-3"><div className="flex flex-1 items-center gap-2 rounded-xl bg-[#121212] p-3 text-xs text-[#999]"><Mail className="h-4 w-4 text-[#86efac]"/>Email</div><div className="flex flex-1 items-center gap-2 rounded-xl bg-[#121212] p-3 text-xs text-[#999]"><MessageSquare className="h-4 w-4"/>SMS</div></div></div></div></div>
 </FinancePageShell>}
