"use client"
import { useState } from "react"
import { Bell, Bot, Building2, Check, Plug, Shield, Users } from "lucide-react"
import { FinancePageShell } from "@/components/finance-page-shell"
const tabs=[Building2,Users,Bot,Bell,Plug,Shield]; const names=["Workspace","Team","AI processing","Notifications","Integrations","Security"]
export default function Settings(){const [saved,setSaved]=useState(false);return <FinancePageShell title="Settings" description="Manage how your finance workspace operates.">
 <div className="grid gap-5 lg:grid-cols-[240px_1fr]"><div className="h-fit rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-2">{names.map((n,i)=>{const I=tabs[i];return <button key={n} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-xs ${i===0?'bg-[#1a1a1a] text-white':'text-[#666] hover:text-white'}`}><I className={`h-4 w-4 ${i===0?'text-[#86efac]':''}`}/>{n}</button>})}</div>
 <div className="rounded-2xl border border-white/[0.04] bg-[#0d0d0d] p-6"><div className="border-b border-[#202020] pb-5"><h2 className="text-lg font-medium">Workspace details</h2><p className="mt-1 text-xs text-[#666]">Information used on reports and outbound messages.</p></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Workspace name" value="Finance Control"/><Field label="Legal business name" value="Finance Control Ltd."/><Field label="Default currency" value="USD — US Dollar"/><Field label="Timezone" value="Africa/Kampala (UTC+3)"/><Field label="Tax identification number" value="TIN-10482930"/><Field label="Financial year starts" value="January"/></div><div className="mt-7 border-t border-[#202020] pt-6"><h3 className="text-sm font-medium">Brand mark</h3><div className="mt-4 flex items-center gap-4"><span className="grid h-14 w-14 place-items-center rounded-xl bg-[#86efac] text-lg font-bold text-black">FC</span><button className="rounded-xl border border-[#292929] px-4 py-2.5 text-xs text-[#888]">Upload new</button></div></div><div className="mt-7 flex justify-end"><button onClick={()=>setSaved(true)} className="flex h-11 items-center gap-2 rounded-xl bg-[#86efac] px-5 text-xs font-semibold text-black">{saved&&<Check className="h-4 w-4"/>}{saved?'Saved':'Save changes'}</button></div></div></div>
 </FinancePageShell>}
function Field({label,value}:{label:string,value:string}){return <label><span className="mb-2 block text-[11px] text-[#777]">{label}</span><input defaultValue={value} className="h-11 w-full rounded-xl border border-[#262626] bg-[#121212] px-3 text-xs text-[#ddd] outline-none focus:border-[#86efac]/40"/></label>}
